例文の難易度を変更できるようにした
illionillion/RAY-BOON pull request #69
Opened 2023-06-29 12:13 UTC by takeki-99

設定画面でChatGPTが返す例文の難易度を変更
できるようにした.

バックエンドとの連携はまだできていない.

2023-06-30 02:22 UTC, illionillion reviewed
4点レビューしました！

2023-06-30 02:22 UTC, illionillion commented on src/screens/Setting/UI/SettingCon.tsx
> +  const [difficulty, setDifficulty] = useState<'easy' | 'normal' | 'hard'>('normal');
17行目に移動させて、state類はまとめて記述してください

2023-06-30 02:22 UTC, illionillion commented on src/screens/Setting/UI/SettingPre.tsx
> +  difficulty: "easy" | "normal" | "hard";
変数類は上、関数類は下で分けて記述した方がいいと思います。

2023-06-30 02:22 UTC, illionillion commented on src/screens/Setting/UI/SettingPre.tsx
> +        <RadioButton.Android
ここのコードはiOSでも問題なく動きますか？
```
<RadioButton.Android
```

2023-06-30 02:22 UTC, illionillion commented on src/screens/Setting/UI/SettingPre.tsx
> +        <Text>簡単</Text>
HTMLの`label`タグのようにテキストをクリックしてもラジオボタンにチェックが入るようにした方がいいと思います。

https://developer.mozilla.org/ja/docs/Web/HTML/Element/label

2023-06-30 02:23 UTC, illionillion commented
@takeki-99 コンフリクトが起こっているみたいなので、ある程度キリの良いところで修正しようと思います。

2023-07-05 12:55 UTC, takeki-99 commented on src/screens/Setting/UI/SettingPre.tsx
> +        <RadioButton.Android
大丈夫です！

2023-08-12 00:43 UTC, illionillion requested changes
@takeki-99 
設定画面のラジオボタンで、

- [x] 普通から簡単に変更できない
- [ ] 普通から難しいに変更できるが、難しいから普通と簡単に変更できない

というバグがAndroidで起こっているので修正お願いします。

<div><video controls src="https://github.com/illionillion/RAY-BOON/assets/60034520/961dd025-49d6-4b27-af65-bd769db26c9b" muted="false"></video></div>

2023-08-12 00:43 UTC, illionillion commented on src/screens/FlashCardsView/UI/FlashCardsViewCon.tsx
> +import { generateExampleReturn } from '../../../lib/createExample';
同じimportがあるので削除お願いします🙇

2023-08-17 11:52 UTC, takeki-99 commented on src/screens/FlashCardsView/UI/FlashCardsViewCon.tsx
> +import { generateExampleReturn } from '../../../lib/createExample';
削除しました

2023-08-17 11:53 UTC, takeki-99 commented
@illionillion バグを修正しました。確認お願いします!

2023-08-18 01:42 UTC, illionillion requested changes

2023-08-18 01:42 UTC, illionillion commented on src/screens/Setting/UI/SettingPre.tsx
> +        <TouchableWithoutFeedback onPress={() => setDifficulty("normal")}>
Androidではラジオボタン外のラベル部分のタッチが機能しないので修正お願いします。

<div><video controls src="https://github.com/illionillion/RAY-BOON/assets/60034520/92868ca9-5673-4197-a9c8-d848fde212fa" muted="false"></video></div>

`RadioButton.Android`から`RadioButton.Item`に変えて`label`属性でタッチできるラベルを作ってもいいかもしれません。

https://zenn.dev/knaka0209/books/cd1518009314d2/viewer/5df99f

2023-08-24 10:58 UTC, takeki-99 commented
@illionillion 修正しました！

2023-08-24 12:46 UTC, illionillion commented
> @illionillion 修正しました！

@takeki-99 
ラジオボタンの挙動は問題ないです！！
ラジオボタンで選択した内容がアプリをリロードすると消えてしまうので、消えないように永続化する処理だけ追加お願いします！！

2023-08-24 13:22 UTC, illionillion commented
> @illionillion よろしくお願いします

@takeki-99 LGTM!! お疲れ様です！！
問題ないのでマージします！！

2023-08-24 13:23 UTC, merged